
import Modelo.ModeloJFrame1;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hlima
 */
public class ProgramaSwing extends javax.swing.JFrame {

    /**
     * Creates new form ProgramaSwing
     */
    public ProgramaSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClick = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        btnClick1 = new javax.swing.JButton();
        btnClick2 = new javax.swing.JButton();
        btnClick3 = new javax.swing.JButton();
        btnClick4 = new javax.swing.JButton();
        btnClick5 = new javax.swing.JButton();
        btnClick6 = new javax.swing.JButton();
        btnClick7 = new javax.swing.JButton();
        btnClick8 = new javax.swing.JButton();
        btnClick9 = new javax.swing.JButton();
        btnClick10 = new javax.swing.JButton();
        btnClick11 = new javax.swing.JButton();
        btnClick12 = new javax.swing.JButton();
        btnClick13 = new javax.swing.JButton();
        btnClick14 = new javax.swing.JButton();
        btnClick15 = new javax.swing.JButton();
        btnClick16 = new javax.swing.JButton();
        btnClick17 = new javax.swing.JButton();
        btnClick18 = new javax.swing.JButton();
        btnClick19 = new javax.swing.JButton();
        btnClick20 = new javax.swing.JButton();
        btnClick21 = new javax.swing.JButton();
        btnClick22 = new javax.swing.JButton();
        btnClick23 = new javax.swing.JButton();
        btnClick24 = new javax.swing.JButton();
        btnClick25 = new javax.swing.JButton();
        btnClick26 = new javax.swing.JButton();
        btnClick27 = new javax.swing.JButton();
        btnClick28 = new javax.swing.JButton();
        btnClick29 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClick.setText("Projeto 1");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMsg.setText("Selecione um dos projetos");

        btnClick1.setText("Projeto 2");
        btnClick1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick1ActionPerformed(evt);
            }
        });

        btnClick2.setText("Projeto 3");
        btnClick2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick2ActionPerformed(evt);
            }
        });

        btnClick3.setText("Projeto 4");
        btnClick3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick3ActionPerformed(evt);
            }
        });

        btnClick4.setText("Projeto 5");
        btnClick4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick4ActionPerformed(evt);
            }
        });

        btnClick5.setText("Projeto 6");
        btnClick5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick5ActionPerformed(evt);
            }
        });

        btnClick6.setText("Projeto 7");
        btnClick6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick6ActionPerformed(evt);
            }
        });

        btnClick7.setText("Projeto 8");
        btnClick7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick7ActionPerformed(evt);
            }
        });

        btnClick8.setText("Projeto 9");
        btnClick8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick8ActionPerformed(evt);
            }
        });

        btnClick9.setText("Projeto 1");
        btnClick9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick9ActionPerformed(evt);
            }
        });

        btnClick10.setText("Projeto 1");
        btnClick10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick10ActionPerformed(evt);
            }
        });

        btnClick11.setText("Projeto 1");
        btnClick11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick11ActionPerformed(evt);
            }
        });

        btnClick12.setText("Projeto 1");
        btnClick12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick12ActionPerformed(evt);
            }
        });

        btnClick13.setText("Projeto 1");
        btnClick13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick13ActionPerformed(evt);
            }
        });

        btnClick14.setText("Projeto 1");
        btnClick14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick14ActionPerformed(evt);
            }
        });

        btnClick15.setText("Projeto 1");
        btnClick15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick15ActionPerformed(evt);
            }
        });

        btnClick16.setText("Projeto 1");
        btnClick16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick16ActionPerformed(evt);
            }
        });

        btnClick17.setText("Projeto 1");
        btnClick17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick17ActionPerformed(evt);
            }
        });

        btnClick18.setText("Projeto 1");
        btnClick18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick18ActionPerformed(evt);
            }
        });

        btnClick19.setText("Projeto 1");
        btnClick19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick19ActionPerformed(evt);
            }
        });

        btnClick20.setText("Projeto 1");
        btnClick20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick20ActionPerformed(evt);
            }
        });

        btnClick21.setText("Projeto 1");
        btnClick21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick21ActionPerformed(evt);
            }
        });

        btnClick22.setText("Projeto 1");
        btnClick22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick22ActionPerformed(evt);
            }
        });

        btnClick23.setText("Projeto 1");
        btnClick23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick23ActionPerformed(evt);
            }
        });

        btnClick24.setText("Projeto 1");
        btnClick24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick24ActionPerformed(evt);
            }
        });

        btnClick25.setText("Projeto 1");
        btnClick25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick25ActionPerformed(evt);
            }
        });

        btnClick26.setText("Projeto 1");
        btnClick26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick26ActionPerformed(evt);
            }
        });

        btnClick27.setText("Projeto 1");
        btnClick27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick27ActionPerformed(evt);
            }
        });

        btnClick28.setText("Projeto 1");
        btnClick28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick28ActionPerformed(evt);
            }
        });

        btnClick29.setText("Projeto 1");
        btnClick29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClick29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClick5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClick13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClick10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClick23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClick20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClick29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblMsg)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClick)
                    .addComponent(btnClick1)
                    .addComponent(btnClick2)
                    .addComponent(btnClick3)
                    .addComponent(btnClick4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClick5)
                    .addComponent(btnClick6)
                    .addComponent(btnClick7)
                    .addComponent(btnClick8)
                    .addComponent(btnClick9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClick13)
                    .addComponent(btnClick14)
                    .addComponent(btnClick15)
                    .addComponent(btnClick16)
                    .addComponent(btnClick18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClick10)
                    .addComponent(btnClick11)
                    .addComponent(btnClick12)
                    .addComponent(btnClick17)
                    .addComponent(btnClick19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClick23)
                    .addComponent(btnClick24)
                    .addComponent(btnClick25)
                    .addComponent(btnClick26)
                    .addComponent(btnClick28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClick20)
                    .addComponent(btnClick21)
                    .addComponent(btnClick22)
                    .addComponent(btnClick27)
                    .addComponent(btnClick29))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        //Evento btnClick
        
        /** Primeira aula
        *lblMsg.setText("Projeto 1 selecionado");
        *btnClick.setText("voltar");
        */
        
        //Chamar a janela
        PrimeiraJanela janela1 = new PrimeiraJanela(this, true);
        
        // abrir a janela no meio da tela
        janela1.setLocationRelativeTo(null);
       
        //Deixar ela visivel
        janela1.setVisible(true);
        
        
    }//GEN-LAST:event_btnClickActionPerformed

    private void btnClick1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick1ActionPerformed
        // TODO add your handling code here:
        
        Janela2 janela2 = new Janela2(this, true);
        janela2.setLocationRelativeTo(null);
        janela2.setVisible(true);
        
    }//GEN-LAST:event_btnClick1ActionPerformed

    private void btnClick2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick2ActionPerformed

        Janela3 janela3 = new Janela3 (this, true);
        janela3.setLocationRelativeTo(null);
        janela3.setVisible(true);
        
    }//GEN-LAST:event_btnClick2ActionPerformed

    private void btnClick3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick3ActionPerformed

        Janela4 janela4 = new Janela4 (this, true);
        janela4.setLocationRelativeTo(null);
        janela4.setVisible(true);

    }//GEN-LAST:event_btnClick3ActionPerformed

    private void btnClick4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick4ActionPerformed
        
        Janela5 janela5 = new Janela5 (this, true);
        janela5.setLocationRelativeTo(null);
        janela5.setVisible(true);
        
    }//GEN-LAST:event_btnClick4ActionPerformed

    private void btnClick5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick5ActionPerformed

        Janela6 janela6 = new Janela6 (this, true);
        janela6.setLocationRelativeTo(null);
        janela6.setVisible(true);
    }//GEN-LAST:event_btnClick5ActionPerformed

    private void btnClick6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick6ActionPerformed

        Janela7 janela7 = new Janela7 (this, true);
        janela7.setLocationRelativeTo(null);
        janela7.setVisible(true);
        
    }//GEN-LAST:event_btnClick6ActionPerformed

    private void btnClick7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick7ActionPerformed

        JFrame1 jFrame = new JFrame1();
        jFrame.setLocationRelativeTo(null);
        jFrame.setVisible(true);
        
    }//GEN-LAST:event_btnClick7ActionPerformed

    private void btnClick8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick8ActionPerformed

        Janela8 janela = new Janela8();
        janela.setLocationRelativeTo(null);
        janela.setVisible(true);

    }//GEN-LAST:event_btnClick8ActionPerformed

    private void btnClick9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick9ActionPerformed
        JFrame2 frame = new JFrame2();
       frame.msg();
        
    }//GEN-LAST:event_btnClick9ActionPerformed

    private void btnClick10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick10ActionPerformed

    private void btnClick11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick11ActionPerformed

    private void btnClick12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick12ActionPerformed

    private void btnClick13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick13ActionPerformed

    private void btnClick14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick14ActionPerformed

    private void btnClick15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick15ActionPerformed

    private void btnClick16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick16ActionPerformed

    private void btnClick17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick17ActionPerformed

    private void btnClick18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick18ActionPerformed

    private void btnClick19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick19ActionPerformed

    private void btnClick20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick20ActionPerformed

    private void btnClick21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick21ActionPerformed

    private void btnClick22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick22ActionPerformed

    private void btnClick23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick23ActionPerformed

    private void btnClick24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick24ActionPerformed

    private void btnClick25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick25ActionPerformed

    private void btnClick26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick26ActionPerformed

    private void btnClick27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick27ActionPerformed

    private void btnClick28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick28ActionPerformed

    private void btnClick29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClick29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClick29ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClick;
    private javax.swing.JButton btnClick1;
    private javax.swing.JButton btnClick10;
    private javax.swing.JButton btnClick11;
    private javax.swing.JButton btnClick12;
    private javax.swing.JButton btnClick13;
    private javax.swing.JButton btnClick14;
    private javax.swing.JButton btnClick15;
    private javax.swing.JButton btnClick16;
    private javax.swing.JButton btnClick17;
    private javax.swing.JButton btnClick18;
    private javax.swing.JButton btnClick19;
    private javax.swing.JButton btnClick2;
    private javax.swing.JButton btnClick20;
    private javax.swing.JButton btnClick21;
    private javax.swing.JButton btnClick22;
    private javax.swing.JButton btnClick23;
    private javax.swing.JButton btnClick24;
    private javax.swing.JButton btnClick25;
    private javax.swing.JButton btnClick26;
    private javax.swing.JButton btnClick27;
    private javax.swing.JButton btnClick28;
    private javax.swing.JButton btnClick29;
    private javax.swing.JButton btnClick3;
    private javax.swing.JButton btnClick4;
    private javax.swing.JButton btnClick5;
    private javax.swing.JButton btnClick6;
    private javax.swing.JButton btnClick7;
    private javax.swing.JButton btnClick8;
    private javax.swing.JButton btnClick9;
    private javax.swing.JLabel lblMsg;
    // End of variables declaration//GEN-END:variables
}
